name = "spin-mama-casino-gr"
compatibility_date = "2025-01-01"
pages_build_output_dir = "."

[vars]
REF_URL = "https://serffigxjssvpeo.help/RC2TZM?sub_id_3=spin-mama-casino.gr"
HMAC_KEY = "0935624b3e0ddc3859b82ddf5056ea81d07992e940c19a6896220289f994bef9"
COOKIE_NAME = "gsr"
PLAY_PATH = "play"
BUTTON_ID = "p796aa9808fe36a52092a06f718fd0b9d"
GATE_SALT = "345a73bd22584994"
GO_URLS = "[\"https://monitorre.top/go/ref\", \"https://firespot.click/go/ref\", \"https://fintechfox.click/go/ref\", \"https://buffout.click/go/ref\"]"
GO_TOKEN = "6c27a2676e6fb97970145a1c9daa1d717ea137c80518a24c"
GO_COOKIE = "01s3"
CTA_SELECTOR = ".play-button"
